name: PR Merge Comment

on:
  pull_request:
    types: [closed]

jobs:
  check-prs:
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }} # Log the branch being checked out
      env:
        GITHUB_REF: ${{ github.ref }} # Log the GitHub ref

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14' # Adjust the version if necessary
      env:
        NODE_VERSION: '14' # Log the Node.js version

    - name: Count merged PRs
      id: count-prs
      run: |
        AUTHOR=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
        REPO=${{ github.repository }}
        TOKEN=${{ secrets.GITHUB_TOKEN }}
        echo "Author: $AUTHOR" # Log the author of the PR
        echo "Repository: $REPO" # Log the repository
        echo "Token: $TOKEN" # Log the GitHub token
        PR_COUNT=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/$REPO/pulls?state=closed" | jq "[.[] | select(.merged_at != null and .user.login == \"$AUTHOR\")] | length")
        echo "PR Count: $PR_COUNT" # Log the PR count
        echo "::set-output name=pr_count::$PR_COUNT"

    - name: Comment on the PR
      if: steps.count-prs.outputs.pr_count != '0'
      uses: actions/github-script@v6
      with:
        script: |
          const prCount = ${{ steps.count-prs.outputs.pr_count }};
          let message;
          if (prCount == 1) {
            message = '1 PR merged successfully!';
          } else if (prCount == 2) {
            message = 'You have merged 2 PRs successfully!';
          } else {
            message = `Excellent! You have merged ${prCount} PRs!`;
          }
          console.log("PR Count:", prCount); // Log the PR count
          console.log("Message:", message); // Log the comment message
          github.rest.issues.createComment({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });
