name: PR Merge Comment

on:
  pull_request:
    types: [closed]

jobs:
  check-prs:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Count merged PRs
        id: count-prs
        run: |
          AUTHOR=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
          REPO=${{ github.repository }}
          TOKEN=${{ secrets.PAT_TOKEN }}
          PR_COUNT=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/$REPO/pulls?state=closed" | jq "[.[] | select(.merged_at != null and .user.login == \"$AUTHOR\")] | length")
          echo "::set-output name=pr_count::$PR_COUNT"
          echo "::set-output name=author::$AUTHOR"

      - name: Comment on the PR
        uses: actions/github-script@v6
        with:
          script: |
            const prCount = parseInt('${{ steps.count-prs.outputs.pr_count }}');
            const author = '${{ steps.count-prs.outputs.author }}';
            const mention = '@HardikGoyal2003'; // Mention for HardikGoyal2003
            let message;
            if (prCount === 1) {
              message = `@${author} 1 PR merged successfully! ${mention}`;
            } else if (prCount === 2) {
              message = `@${author} You have merged 2 PRs successfully! ${mention}`;
            } else {
              message = `Excellent! @${author} You have merged ${prCount} PRs! ${mention}`;
            }
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message,
              token: process.env.PAT_TOKEN // Use the PAT token
            });
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
